# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 05:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='imagerprofile',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='imagerprofile',
            old_name='region',
            new_name='location',
        ),
        migrations.AddField(
            model_name='imagerprofile',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='imagerprofile',
            name='friends',
            field=models.ManyToManyField(related_name='friend_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagerprofile',
            name='photography_type',
            field=models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape'), ('nature', 'Nature'), ('family', 'Family'), ('travel', 'Travel'), ('art', 'Art'), ('food', 'Food'), ('i_suck', 'Selfies')], default='nature', max_length=30),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='camera',
            field=models.TextField(default=''),
        ),
    ]
