# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0003_auto_20160415_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagerprofile',
            old_name='location',
            new_name='region',
        ),
    ]
