# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0004_auto_20160416_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='region',
            field=models.CharField(default='us', max_length=30),
        ),
    ]
